name: Deploy To Server

on:
  push:
    branchs:
      - master

jobs:
  deploy-production-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.PORT }}
          script: git push ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}/home/vuttr_backend/repo master
