name: Deploy To Server

on:
  push:
    branchs:
      - master

jobs:
  deploy-production-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/scp-action@master
        env:
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          HOST: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: ${{ secrets.PORT }}
        with:
          source: "."
          target: "vuttr_backend/www/"
