name: Deploy To Server

on:
  push:
    branchs:
      - master

jobs:
  deploy-production-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy Env File Configuration

      - uses: easingthemes/ssh-deploy@v2.0.7
      - env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
