name: Testes E Code Sniffer

on:
  push:
    branchs:
      - master
      - develop
      - feature/*

jobs:
  laravel-tests-codesniffer:
    env:
      working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Env File Configuration
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
        working-directory: ${{ env.working-directory }}
      - name: Install Composers Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: ${{ env.working-directory }}
      - name: Genarate Laravel Key
        run: php artisan key:generate
        working-directory: ${{ env.working-directory }}
      - name: Run Migrations
        run: php artisan migrate
        working-directory: ${{ env.working-directory }}
      - name: Run Tests And Code Coverage
        run: ./vendor/bin/phpunit -c phpunit.xml.dist
        working-directory: ${{ env.working-directory }}
      - name: Run Code Sniffer
        run: ./vendor/bin/phpcs
        working-directory: ${{ env.working-directory }}
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
